/**
 * Cross-language hash parity between `src/lib/kb/normalise.ts` and
 * `kb-scripts/lib_kb.py`.
 *
 * WHY THIS IS A GATE AND NOT A NICETY. The drift baseline in
 * `kb-data/_sources.json` was computed by the Python. If the TypeScript port
 * normalises one character differently, every source reads as drifted every
 * day, the queue fills with noise, and `/admin/kb` is abandoned in week one —
 * the exact failure `specs/14` predicts about a different mechanism.
 *
 * `tests/fixtures/normalise-parity.json` was GENERATED BY THE PYTHON, not by
 * this implementation: each case carries the input, the Python's normalised
 * output and the Python's SHA-256. The fixtures cover every construct the
 * normaliser touches — dropped tags, block ends, `<br>`, table cells, named and
 * numeric entities, an unknown entity, non-breaking and unicode spaces, and
 * each of the five volatile patterns.
 *
 * Beyond these fixtures, parity was verified during the build against the **59
 * real captured board pages** in `phase-4-revenue/stateready/research/raw/`:
 * 59 of 59 produced byte-identical normalised text and identical hashes. That
 * run found one genuine bug — Python's `Next Board Meeting.{0,80}` is not
 * dot-all, so a `[\s\S]` port ate 80 characters across the line break and put
 * every TSBPE page 80 bytes short. The corpus is not committed here (it belongs
 * to the research tree); the finding is recorded in BUILD.md.
 */

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { contentHash, excerpts, htmlToText, normalise, unescapeHtml } from '../src/lib/kb/normalise';

type ParityCase = { input: string; normalised: string; sha256: string };

const fixtures = JSON.parse(
  readFileSync(join(dirname(fileURLToPath(import.meta.url)), 'fixtures', 'normalise-parity.json'), 'utf8'),
) as Record<string, ParityCase>;

describe('normalisation parity with kb-scripts/lib_kb.py', () => {
  it('covers thirteen constructs', () => {
    expect(Object.keys(fixtures).length).toBe(13);
  });

  for (const [name, testCase] of Object.entries(fixtures)) {
    it(`${name} — identical text and identical hash`, () => {
      const produced = normalise(testCase.input);
      expect(produced).toBe(testCase.normalised);
      expect(contentHash(produced)).toBe(testCase.sha256);
    });
  }
});

describe('the normaliser is deliberately lossy in the right places', () => {
  it('a re-theme is not a rule change: attributes, classes and inline markup vanish', () => {
    const before = '<div class="old"><p>Renewal fee is $65.</p></div>';
    const after = '<section id="new" data-v="7"><p style="color:#000"><strong>Renewal fee is $65.</strong></p></section>';
    expect(normalise(before)).toBe(normalise(after));
  });

  it('a real content change survives', () => {
    expect(normalise('<p>Renewal fee is $65.</p>')).not.toBe(normalise('<p>Renewal fee is $80.</p>'));
  });

  it('leaves an unknown named entity verbatim rather than guessing at it', () => {
    expect(unescapeHtml('&unknownref;')).toBe('&unknownref;');
    expect(unescapeHtml('&#8212;')).toBe('—');
    expect(unescapeHtml('&#x2014;')).toBe('—');
  });

  it('turns table cells into a pipe-separated reading, as the Python does', () => {
    expect(htmlToText('<tr><td>Class A</td><td>$115</td></tr>')).toBe('| Class A\n| $115');
  });
});

describe('bounded excerpts for the diff screen', () => {
  it('stores a head and, only past 4000 characters, a tail', () => {
    const short = excerpts('a'.repeat(100));
    expect(short.head).toHaveLength(100);
    expect(short.tail).toBe('');

    const long = excerpts(`${'a'.repeat(4000)}${'b'.repeat(1000)}`);
    expect(long.head).toHaveLength(4000);
    expect(long.tail).toHaveLength(4000);
    expect(long.tail.endsWith('b')).toBe(true);
  });
});
