-- M6 — the dashboard's own index. `specs/06` §4, verbatim:
--
--     CREATE INDEX vendors_dashboard ON vendors
--       (org_id, archived_at, status, earliest_required_expiry);
--
-- WHY A FOURTH INDEX ON `vendors` when three already exist. The counters and
-- the table are computed from ONE predicate module (`src/lib/repos/dashboard.ts`)
-- so that they cannot drift, and that predicate is always the same four
-- columns in the same order: this org, not archived, in this status, soonest
-- required expiry first. `vendors_org_status_idx` cannot serve it because it
-- does not carry `archived_at`, so every counter query would still have to
-- re-check the heap row — which is the difference between the 200 ms
-- `specs/06` §11 asks for at 5,000 vendors and a sequential scan.
--
-- Generated by `drizzle-kit generate` from `schema.ts`, so `meta/0003_snapshot.json`
-- stays in step; only the file name and this comment were added by hand.

CREATE INDEX "vendors_dashboard" ON "vendors" USING btree ("org_id","archived_at","status","earliest_required_expiry");
