-- M7 — the org's reminder settings (`specs/07` §5). Added by sub-wave B agent B3.
-- Generated by `drizzle-kit generate` from `schema.ts`; only the file name and
-- this header were written by hand. A TABLE rather than four columns on
-- `org_settings`: three agents are editing that file in parallel and an
-- appended table is a conflict-free hunk, while widening a shared row is not.

CREATE TABLE "reminder_settings" (
	"org_id" text PRIMARY KEY NOT NULL,
	"ladder" jsonb,
	"sending_name" text,
	"reply_to_email" text,
	"weekly_digest_day" integer DEFAULT 1 NOT NULL,
	"paused" boolean DEFAULT false NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "reminder_settings" ADD CONSTRAINT "reminder_settings_org_id_organisations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organisations"("id") ON DELETE cascade ON UPDATE no action;