/**
 * GENERATED FROM `phase-4-revenue/certly/specs/00-event-vocabulary.md`.
 * Do not edit by hand: run `npm run events:check -- --write`.
 *
 * `specs/00` §1 is the single source of every event name in Certly, and this
 * union is how a typo becomes a compile error instead of a silent hole in a
 * funnel. A name that is not here does not exist; a name in §4 (retired) is
 * refused by `events:check`.
 */

/** §2 — product events, owned by the spec that defines the emission point. */
export const PRODUCT_EVENTS = [
  'signup_started',
  'magic_link_requested',
  'magic_link_sent',
  'magic_link_consumed',
  'magic_link_failed',
  'org_created',
  'login_succeeded',
  'signout',
  'template_library_opened',
  'template_previewed',
  'template_source_opened',
  'template_applied',
  'requirement_set_created',
  'requirement_added',
  'requirement_edited',
  'requirement_deleted',
  'requirement_set_assigned',
  'template_update_previewed',
  'vendor_type_created',
  'vendor_created',
  'vendor_updated',
  'vendor_archived',
  'csv_import_started',
  'csv_columns_mapped',
  'csv_import_completed',
  'csv_import_failed',
  'vendor_missing_contact_prompt_shown',
  'coi_upload_started',
  'coi_uploaded',
  'coi_upload_rejected',
  'coi_duplicate_detected',
  'extraction_started',
  'extraction_succeeded',
  'extraction_failed',
  'extraction_retried',
  'document_rejected',
  'review_opened',
  'review_field_corrected',
  'review_completed',
  'certificate_promoted',
  'comparison_run',
  'gap_detected',
  'asserted_only_detected',
  'explanation_opened',
  'reevaluation_triggered',
  'vendor_status_changed',
  'dashboard_viewed',
  'dashboard_filtered',
  'dashboard_sorted',
  'vendor_opened_from_dashboard',
  'bulk_remind_clicked',
  'review_queue_opened',
  'reminder_scheduled',
  'reminder_sent',
  'reminder_delivered',
  'reminder_bounced',
  'reminder_complained',
  'reminder_suppressed',
  'reminder_skipped',
  'reminder_cancelled',
  'reminder_clicked',
  'reminder_paused',
  'unsubscribed',
  'renewal_received_after_reminder',
  'upload_link_generated',
  'upload_link_opened',
  'upload_link_expired_view',
  'upload_link_revoked_view',
  'vendor_upload_started',
  'vendor_upload_completed',
  'vendor_upload_rejected',
  'vendor_upload_gaps_shown',
  'vendor_upload_second_attempt',
  'activity_viewed',
  'activity_filtered',
  'audit_exported',
  'pricing_viewed',
  'checkout_started',
  'checkout_completed',
  'checkout_abandoned',
  'trial_will_end_email_sent',
  'trial_converted',
  'trial_cancelled',
  'paywall_viewed',
  'pack_added',
  'plan_changed',
  'subscription_past_due',
  'subscription_cancelled',
  'refund_issued',
  'read_only_view',
  'onboarding_started',
  'onboarding_step_completed',
  'onboarding_step_abandoned',
  'vendors_pasted',
  'activated',
  'onboarding_skipped',
  'onboarding_resumed',
  'first_finding_shown',
  'export_dialog_opened',
  'report_generated',
  'report_downloaded',
  'report_share_created',
  'report_share_opened',
  'report_share_revoked',
  'report_failed',
  'settings_viewed',
  'entity_block_changed',
  'alternate_holder_added',
  'member_invited',
  'member_joined',
  'role_changed',
  'member_removed',
  'help_search',
  'help_article_viewed',
  'support_email_sent',
  'data_exported',
  'deletion_requested',
  'deletion_cancelled',
  'legal_page_viewed',
  'gap_report_started',
  'gap_report_files_added',
  'gap_report_email_captured',
  'gap_report_processing',
  'gap_report_ready',
  'gap_report_viewed',
  'gap_report_emailed',
  'gap_report_cta_clicked',
  'gap_report_converted',
  'gap_report_rate_limited',
  'gap_report_capacity_disabled',
] as const;

/** §3 — landing-page events. Anonymous and pre-account, hence the `lp_` prefix. */
export const LANDING_EVENTS = [
  'lp_',
  'lp_view',
  'lp_scroll_depth',
  'lp_hero_cta_click',
  'lp_demo_run',
  'lp_demo_complete',
  'lp_demo_to_cta',
  'lp_visual_view',
  'lp_sample_report_open',
  'lp_pricing_view',
  'lp_plan_select',
  'lp_faq_open',
  'lp_gap_report_start',
  'lp_gap_report_submit',
  'lp_gap_report_delivered',
  'lp_gap_report_waitlist',
] as const;

/** §4 — names that must never appear again. */
export const RETIRED_EVENTS = [
  'first_status_rendered',
  'dialect_chosen',
  'requirement_template_created',
  'parties_imported',
  'document_received',
  'extraction_completed',
  'review_accepted',
  'renewal_received',
  'status_changed',
  'gap_report_exported',
  'magic_link_opened',
  'trial_ended',
  'subscription_active',
  'onboarding_abandoned',
  'requirement_source_opened',
  'report_shared_link_created',
  'trial_started',
  'tier_limit_reached',
  'signup_start',
  'trial_start',
  'paid',
  'gap_report_cost_cents',
  'audit_event_written',
  'endorsement_uploaded',
  'clause_pasted',
] as const;

export type ProductEventName = (typeof PRODUCT_EVENTS)[number];
export type LandingEventName = (typeof LANDING_EVENTS)[number];
export type EventName = ProductEventName | LandingEventName;

export const EVENT_NAMES: readonly EventName[] = [...PRODUCT_EVENTS, ...LANDING_EVENTS];

const REGISTRY = new Set<string>(EVENT_NAMES);

/** Runtime guard for the one place a name arrives as data: `/api/events`. */
export function isEventName(value: unknown): value is EventName {
  return typeof value === 'string' && REGISTRY.has(value);
}

export function isLandingEventName(value: unknown): value is LandingEventName {
  return typeof value === 'string' && (LANDING_EVENTS as readonly string[]).includes(value);
}
