/**
 * The disclaimers, as COMPONENTS rather than as copy.
 *
 * KNOWLEDGE_BASE §9 gives three surfaces and three texts; PLAN.md A10 requires
 * one on every screen and every document that shows a rate. Making them
 * components — and making the rate component the disclaimer component's
 * neighbour on every page — is what turns "we put a disclaimer on it" from an
 * editorial habit into something a test can check.
 *
 * WHAT NO SURFACE HERE MAY EVER SAY (WL-11 V4, and `tests/naming.test.ts`
 * fails the build on any of it): a penalty amount, a claimed rate of success,
 * or any promise that a filing will be accepted. There is deliberately no prop, slot or convention that
 * would make one easy to add.
 */

import Link from 'next/link';

import { productName } from '@/env';

/** §9.3, the standing disclaimer, in full. Never collapsed on a public result
 *  page (WL-00 V7). */
export function StandingDisclaimer({ compact = false }: { compact?: boolean }) {
  const product = productName();
  return (
    <div className="wl-disclaimer" data-testid="standing-disclaimer">
      <p>
        <strong>
          {product} is an information tool, not legal or accounting advice, and not a substitute for
          the wage determination incorporated into your contract.
        </strong>
      </p>
      {compact ? null : (
        <>
          <p>
            The rates shown are our reproduction of published U.S. Department of Labor Davis-Bacon
            wage determinations, retrieved from SAM.gov. Every rate carries the determination number,
            the modification number, the publication date and a link to the official document — check
            it before you file.
          </p>
          <p>
            Choosing the classification for the work a person actually performed is your decision and
            your legal responsibility. {product} does not run payroll, move money, file with anyone,
            or choose classifications for you.{' '}
            <Link href="/help/what-we-do-not-do">What we do not do</Link> ·{' '}
            <Link href="/legal/disclaimer">the full disclaimer</Link>.
          </p>
        </>
      )}
    </div>
  );
}

/** §9.1 — inline, wherever a rate appears and a full card would be too heavy. */
export function InlineDisclaimer() {
  return (
    <p className="wl-disclaimer" data-testid="inline-disclaimer">
      Rates are our reproduction of a published U.S. Department of Labor wage determination, shown
      with its number, modification and date. Verify against the determination incorporated into your
      contract before you file.
    </p>
  );
}

/**
 * §9.2 — the footer of every generated WH-347 and Statement of Compliance,
 * verbatim. Exported as a STRING because it is stamped into a PDF, and asserted
 * on the extracted text (WL-11 V2). WL-06's agent renders it; it lives here so
 * there is exactly one copy of the words.
 */
export function documentFooterText(input: {
  productName: string;
  productUrl: string;
  generatedAt: Date;
  wdNumber: string;
  modificationNumber: number;
  publicationDate: string;
}): string {
  return [
    `Generated by ${input.productName} (${input.productUrl}) on ${input.generatedAt.toISOString()}`,
    `from ${input.wdNumber} mod ${input.modificationNumber} (published ${input.publicationDate}),`,
    'retrieved from SAM.gov. This is a reproduction of U.S. Department of Labor form WH-347',
    '(Rev. January 2025, OMB 1235-0008); it is not an official DOL document.',
    'The contractor signing this form is solely responsible for the accuracy of every entry on it,',
    'including the labor classifications.',
  ].join(' ');
}
