#!/usr/bin/env python3
"""Validate every prospects.csv under phase-3-acquisition/prospects/, report counts,
cross-app overlaps and rule violations. Run from the repo root:

    python3 phase-3-acquisition/prospects/scripts/validate_all.py [--write-index]

--write-index rewrites phase-3-acquisition/prospects/INDEX.md with the counts.
"""
import csv, os, re, sys, collections, glob

ROOT = os.path.join('phase-3-acquisition', 'prospects')
COLS = ['app','prospect_type','segment','name','website','location','size_signal',
        'fit_rationale','contact_route','decision_maker_role','source_url','source_type',
        'confidence','collected_on','notes']
TYPES = {'end-customer','partner','channel','excluded'}
CONF = {'verified','secondary','unverified'}
PERSONAL = re.compile(r'@(gmail|yahoo|hotmail|outlook|icloud|proton(mail)?|aol|live|me)\.', re.I)
PHONE = re.compile(r'\(?\b\d{3}\)?[-. ]\d{3}[-. ]\d{4}\b')

def norm(s):
    s = s.lower().strip()
    s = re.sub(r'^(https?://)?(www\.)?', '', s)
    return s.rstrip('/')

def main():
    write_index = '--write-index' in sys.argv
    files = sorted(glob.glob(os.path.join(ROOT, '*', 'prospects.csv')))
    if not files:
        print('no prospects.csv found'); return 1
    problems = []
    per_dir = {}
    all_rows = []
    for f in files:
        d = os.path.basename(os.path.dirname(f))
        with open(f, encoding='utf-8', newline='') as fh:
            rows = list(csv.DictReader(fh))
        if not rows:
            problems.append(f'{d}: empty file'); continue
        if list(rows[0].keys()) != COLS:
            problems.append(f'{d}: bad header {list(rows[0].keys())}')
        seen = set()
        for i, r in enumerate(rows, 2):
            r = {k: (v or '').strip() for k, v in r.items()}
            if not r.get('name') or not r.get('source_url'):
                problems.append(f'{d}:{i}: missing name or source_url')
            if r.get('prospect_type') not in TYPES:
                problems.append(f'{d}:{i}: bad prospect_type {r.get("prospect_type")!r}')
            if r.get('confidence') not in CONF:
                problems.append(f'{d}:{i}: bad confidence {r.get("confidence")!r}')
            blob = ' '.join(r.get(k, '') for k in ('contact_route', 'notes', 'fit_rationale'))
            if PERSONAL.search(blob):
                problems.append(f'{d}:{i}: personal mailbox in row {r["name"]!r}')
            if PHONE.search(r.get('contact_route', '')):
                problems.append(f'{d}:{i}: phone number in contact_route for {r["name"]!r}')
            key = (norm(r.get('name', '')), norm(r.get('website', '')))
            if key in seen:
                problems.append(f'{d}:{i}: duplicate name+website {r["name"]!r}')
            seen.add(key)
            r['_dir'] = d
            all_rows.append(r)
        per_dir[d] = rows
    # counts
    print('=== rows per directory ===')
    total = 0
    idx_lines = ['# Prospect lists: index', '', 'Generated by `scripts/validate_all.py --write-index`.', '',
                 '| directory | rows | end-customer | partner | channel | excluded | verified | secondary | unverified |',
                 '|---|---|---|---|---|---|---|---|---|']
    for d, rows in per_dir.items():
        t = collections.Counter(r['prospect_type'] for r in rows)
        c = collections.Counter(r['confidence'] for r in rows)
        total += len(rows)
        print(f'{d:14s} {len(rows):5d}  ' + '  '.join(f'{k}={t.get(k,0)}' for k in ['end-customer','partner','channel','excluded'])
              + '   ' + '  '.join(f'{k}={c.get(k,0)}' for k in ['verified','secondary','unverified']))
        idx_lines.append(f'| {d} | {len(rows)} | {t.get("end-customer",0)} | {t.get("partner",0)} | {t.get("channel",0)} | {t.get("excluded",0)} | {c.get("verified",0)} | {c.get("secondary",0)} | {c.get("unverified",0)} |')
    print(f'{"TOTAL":14s} {total:5d}')
    idx_lines.append(f'| **total** | **{total}** | | | | | | | |')
    # segments
    print('\n=== segments per directory ===')
    idx_lines += ['', '## Segments', '']
    for d, rows in per_dir.items():
        seg = collections.Counter((r['prospect_type'], r['segment']) for r in rows)
        print(f'-- {d}')
        idx_lines.append(f'### {d}')
        idx_lines.append('')
        idx_lines.append('| type | segment | rows |')
        idx_lines.append('|---|---|---|')
        for (t, s), n in sorted(seg.items(), key=lambda x: (-x[1], x[0])):
            print(f'   {n:4d}  {t:13s} {s}')
            idx_lines.append(f'| {t} | {s} | {n} |')
        idx_lines.append('')
    # cross-app overlaps (same organisation useful to several apps)
    by_key = collections.defaultdict(set)
    for r in all_rows:
        k = norm(r.get('website', '')) or norm(r.get('name', ''))
        if k:
            by_key[k].add(r['_dir'])
    overl = {k: v for k, v in by_key.items() if len(v) > 1}
    print(f'\n=== organisations appearing in more than one list: {len(overl)} ===')
    for k, v in sorted(overl.items(), key=lambda x: -len(x[1]))[:40]:
        print(f'   {k:45s} {sorted(v)}')
    idx_lines += ['## Cross-app overlaps', '', f'{len(overl)} organisations appear in more than one list (same website or name). Top 40:', '',
                  '| organisation | lists |', '|---|---|']
    for k, v in sorted(overl.items(), key=lambda x: -len(x[1]))[:40]:
        idx_lines.append(f'| {k} | {", ".join(sorted(v))} |')
    # problems
    print(f'\n=== problems: {len(problems)} ===')
    for p in problems[:200]:
        print('   ' + p)
    if write_index:
        with open(os.path.join(ROOT, 'INDEX.md'), 'w', encoding='utf-8') as fh:
            fh.write('\n'.join(idx_lines) + '\n')
        print('\nwrote', os.path.join(ROOT, 'INDEX.md'))
    return 1 if problems else 0

if __name__ == '__main__':
    sys.exit(main())
