/**
 * S17 — `/api/artifacts/[id]`, the artifact bytes.
 *
 * AUTHORITY: `ARCHITECTURE.md` §3.1 (the route), I6 (the sha256 IS the identity),
 * `USER_JOURNEY.md` §7.6 ("Artifact generation is deterministic; the object store is
 * a cache of a pure function. Losing it is an availability problem, never a
 * correctness one").
 *
 * ===========================================================================
 * THE BYTES ARE REBUILT AND THEN CHECKED AGAINST THE RECORDED DIGEST
 *
 * The filing stores its inputs and the digest of what those inputs rendered to. This
 * route re-renders and compares. A mismatch is a 409 with both digests printed —
 * never a silent serve of different bytes under the same filing id — because the one
 * thing a certified-payroll archive may not do is hand back a document that is not
 * the document that was signed.
 */

import { NextResponse } from 'next/server';

import { getDb } from '@/db';

import { readAs, requireSession } from '../../../_lib/auth';
import { listArtifacts, rebuildFiling } from '../../../_lib/filings';

export const dynamic = 'force-dynamic';

export async function GET(
  request: Request,
  context: { readonly params: Promise<{ readonly id: string }> },
): Promise<NextResponse> {
  const { id } = await context.params;
  const kind = new URL(request.url).searchParams.get('kind') ?? 'wh347_pdf';
  const session = await requireSession(`/app/filings/${id}`);
  const db = await getDb();

  const view = await readAs(session, async (tx) => {
    const rebuilt = await rebuildFiling(db, tx, id);
    if (rebuilt === null) return null;
    return { rebuilt, artifacts: await listArtifacts(tx, id) };
  });

  if (view === null) {
    return NextResponse.json({ error: 'no such filing on this account' }, { status: 404 });
  }

  if (kind === 'exception_report') {
    return new NextResponse(view.rebuilt.exceptions.join('\n\n'), {
      status: 200,
      headers: {
        'content-type': 'text/plain; charset=utf-8',
        'content-disposition': `attachment; filename="exceptions-${id.slice(0, 8)}.txt"`,
        'cache-control': 'private, no-store',
      },
    });
  }

  if (kind !== 'wh347_pdf') {
    // The CA XML has its own status and its own blocks (§10.2). It is emitted by the
    // filing screen when every one of them clears, and never by guessing here.
    return NextResponse.json(
      {
        error:
          'This artifact is not available for this filing. The California eCPR XML carries its ' +
          'own status, separate from the WH-347, and the filing screen states which condition is ' +
          'unmet.',
      },
      { status: 409 },
    );
  }

  const recorded = view.artifacts.find((artifact) => artifact.kind === 'wh347_pdf');
  if (recorded && recorded.sha256 !== view.rebuilt.pdfSha256) {
    return NextResponse.json(
      {
        error: 'regenerated bytes do not match the recorded digest',
        recorded: recorded.sha256,
        rebuilt: view.rebuilt.pdfSha256,
        note:
          'Ratepin will not serve a document that is not the document it recorded. Both digests ' +
          'are printed above so the difference is checkable rather than asserted.',
      },
      { status: 409 },
    );
  }

  return new NextResponse(Buffer.from(view.rebuilt.pdf), {
    status: 200,
    headers: {
      'content-type': 'application/pdf',
      'content-disposition': `attachment; filename="wh347-${view.rebuilt.filing.weekEnding}-${id.slice(0, 8)}.pdf"`,
      'cache-control': 'private, no-store',
      'x-ratepin-sha256': view.rebuilt.pdfSha256,
    },
  });
}
