#!/usr/bin/env python3
"""Hand-curated partner / channel / excluded rows for DutyLens.
Every row's website + contact_route comes from raw/partner_check.json or
raw/channel_check.json, i.e. from a page this agent actually opened once.
Rows are (prospect_type, segment, name, probe_url, size_signal, fit_rationale,
decision_maker_role, source_url, source_type, confidence, notes)."""
ROWS = [
# ---------------- freight forwarders / digital freight platforms ----------------
("partner","freight forwarder","Flexport","https://www.flexport.com/","",
 "Digital freight forwarder and customs broker for SMB and mid-market importers; its clients are exactly the importers who need per-SKU HTS and landed-cost answers.",
 "head of partnerships","https://www.flexport.com/","company-site","verified",
 "Also a partial competitor: sells customs brokerage and duty tooling. Treat as referral/bundle partner, not reseller."),
("partner","freight forwarder","Freightos","https://www.freightos.com/","",
 "Freight marketplace used by small importers to book ocean/air; a landed-cost + HTS layer complements its rate comparison.",
 "head of partnerships","https://www.freightos.com/partners/","company-site","verified",""),
("partner","freight forwarder","Forceget Supply Chain Logistics","https://www.forceget.com/","",
 "Digital forwarder marketed to Amazon FBA and DTC sellers importing from China.",
 "head of partnerships","https://www.forceget.com/","company-site","unverified",
 "Site returned HTTP 202 challenge on fetch; company name and positioning taken from the URL only, not from page content."),
("partner","freight forwarder","Unicargo","https://www.unicargo.com/","",
 "Forwarder positioned at ecommerce importers; publishes customs-clearance content aimed at first-time importers.",
 "head of partnerships","https://www.unicargo.com/contact-us/","company-site","verified",""),
("partner","freight forwarder","Shipa Freight (Agility)","https://www.shipafreight.com/","",
 "Online freight forwarder with instant quotes aimed at small shippers.",
 "head of partnerships","https://www.shipafreight.com/contact-us/","company-site","verified",""),
("partner","freight forwarder","Ship4wd","https://ship4wd.com/","",
 "Digital freight forwarder built specifically for SMB importers; same buyer as DutyLens.",
 "head of partnerships","https://ship4wd.com/","company-site","unverified",
 "Site returned HTTP 202 challenge; positioning from search result snippet, page body not parsed."),
("partner","freight forwarder","ExFreight Zeta","https://www.exfreight.com/","",
 "Non-asset digital forwarder serving small and mid-size shippers.",
 "head of partnerships","https://www.exfreight.com/","company-site","verified",""),
# ---------------- 3PL / fulfillment ----------------
("partner","3PL / fulfillment","ShipBob","https://www.shipbob.com/","60+ fulfillment centres (own site)",
 "Largest DTC-focused 3PL; its merchants import from Asia and now owe duty on every parcel. Runs a formal partner programme.",
 "head of partnerships","https://partners.shipbob.com/","company-site","verified",""),
("partner","3PL / fulfillment","ShipMonk","https://www.shipmonk.com/","",
 "3PL for D2C ecommerce brands and subscription boxes; merchant base matches the ICP.",
 "head of partnerships","https://www.shipmonk.com/","company-site","verified",""),
("partner","3PL / fulfillment","Red Stag Fulfillment","https://redstagfulfillment.com/","",
 "3PL for heavy/high-value goods, mostly imported hard goods.",
 "head of partnerships","https://redstagfulfillment.com/contact-us/","company-site","verified",""),
("partner","3PL / fulfillment","Fulfyld","https://www.fulfyld.com/","",
 "Ecommerce 3PL with an published partner programme aimed at DTC brands.",
 "head of partnerships","https://www.fulfyld.com/partners/","company-site","verified",""),
("partner","3PL / fulfillment","Shipfusion","https://www.shipfusion.com/","",
 "Ecommerce 3PL with a partner page; brands it serves import from Asia.",
 "head of partnerships","https://www.shipfusion.com/partners","company-site","verified",""),
("partner","3PL / fulfillment","ShipHero","https://www.shiphero.com/","",
 "WMS + fulfillment network used by DTC brands and other 3PLs; natural embed point for landed-cost data.",
 "head of partnerships","https://www.shiphero.com/partners","company-site","verified",""),
("partner","3PL / fulfillment","Stord","https://www.stord.com/","",
 "Omnichannel fulfillment network for consumer brands.",
 "head of partnerships","sales@stord.com","company-site","verified",""),
("partner","3PL / fulfillment","GoBolt","https://www.gobolt.com/","",
 "3PL for DTC brands in the US and Canada, with a published partner programme.",
 "head of partnerships","https://www.gobolt.com/partners/","company-site","verified",""),
("partner","3PL / fulfillment","Verde Fulfillment USA","https://verdefulfillmentusa.com/","",
 "DTC and B2B 3PL serving mid-size consumer brands.",
 "head of partnerships","sales@verdefulfillmentusa.com","company-site","verified",""),
("partner","3PL / fulfillment","AMS Fulfillment","https://www.amsfulfillment.com/","",
 "eCommerce and B2B order fulfillment provider with a software-partner programme.",
 "head of partnerships","https://www.amsfulfillment.com/business-integrations/software-partner-program/","company-site","verified",""),
("partner","3PL / fulfillment","Barrett Distribution Centers","https://www.barrettdistribution.com/","",
 "Ecommerce 3PL whose apparel and consumer-goods clients import from Asia.",
 "head of partnerships","sales@barrettdistribution.com","company-site","verified",""),
("partner","3PL / fulfillment","FIDELITONE","https://www.fidelitone.com/","",
 "3PL with order fulfillment and last-mile for consumer-goods importers.",
 "head of partnerships","https://www.fidelitone.com/","company-site","verified",""),
("partner","3PL / fulfillment","Bergen Logistics","https://bergenlogistics.com/","",
 "Apparel and accessories 3PL; apparel is the most tariff-exposed HTS chapter set.",
 "head of partnerships","https://bergenlogistics.com/","company-site","verified",""),
# ---------------- China sourcing agents ----------------
("partner","sourcing agent","JingSourcing","https://jingsourcing.com/","claims 4,000+ clients on its own homepage",
 "China sourcing company for US Amazon and DTC sellers; its clients need an HTS code and duty number before they commit to a product.",
 "head of partnerships","https://jingsourcing.com/","company-site","verified",""),
("partner","sourcing agent","Supplyia","https://www.supplyia.com/","",
 "Yiwu-based sourcing company with a US office serving Amazon FBA sellers; publishes a partners page.",
 "head of partnerships","https://www.supplyia.com/partners/","company-site","verified",""),
("partner","sourcing agent","Leeline Sourcing","https://leelinesourcing.com/","claims 6,000+ clients on its own homepage",
 "Sourcing agent for US private-label sellers, with an existing partner programme.",
 "head of partnerships","https://leelinesourcing.com/our-partners/","company-site","verified",""),
("partner","sourcing agent","Sourcify","https://www.sourcify.com/","",
 "US-run sourcing platform connecting DTC brands to overseas factories.",
 "head of partnerships","https://www.sourcify.com/partners/","company-site","verified",""),
("partner","sourcing agent","China 2 West Services","https://www.china2west.com/","",
 "Contract-manufacturing and sourcing firm serving western SMB product companies.",
 "head of partnerships","https://www.china2west.com/","company-site","verified",""),
("partner","sourcing agent","IMEX Sourcing Services","https://imexsourcingservices.com/","",
 "Sourcing and QC firm for ecommerce importers.",
 "head of partnerships","https://imexsourcingservices.com/contact-us-inquiry","company-site","verified",""),
("partner","sourcing agent","Guided Imports","https://guidedimports.com/","",
 "Freight, FBA prep and sourcing support for US importers buying from China.",
 "head of partnerships","https://guidedimports.com/contact/","company-site","verified",""),
("partner","sourcing agent","Maple Sourcing","https://www.maplesourcing.com/","",
 "China sourcing agent with QC services for western SMB buyers.",
 "head of partnerships","sales@maplesourcing.com","company-site","verified",""),
("partner","sourcing agent","BaySource Global","https://baysourceglobal.com/","",
 "US-based China manufacturing and sourcing partner for product companies.",
 "head of partnerships","https://baysourceglobal.com/","company-site","verified",""),
("partner","sourcing agent","B2C Sourcing","https://b2csourcing.com/","",
 "Sourcing service built specifically around the Amazon FBA private-label workflow.",
 "head of partnerships","https://b2csourcing.com/contact/","company-site","verified",""),
("partner","sourcing agent","Dragon Sourcing","https://www.dragonsourcing.com/","",
 "Sourcing company covering China and other emerging markets for western buyers.",
 "head of partnerships","https://www.dragonsourcing.com/","company-site","verified",""),
("partner","sourcing agent","Foshan Sourcing","https://foshansourcing.com/","",
 "China sourcing agent listed on a vetted public list of sourcing companies for private-label sellers.",
 "head of partnerships","https://mywifequitherjob.com/china-sourcing-agent/","list-article","unverified",
 "Own site returned HTTP 202 challenge; only the third-party list entry could be read."),
("partner","sourcing agent","Linc Sourcing","https://www.lincsourcing.com/","",
 "China sourcing agent listed on a vetted public list of sourcing companies for private-label sellers.",
 "head of partnerships","https://mywifequitherjob.com/china-sourcing-agent/","list-article","unverified",
 "Own site returned HTTP 202 challenge; only the third-party list entry could be read."),
("partner","sourcing agent","Meeno Group","https://www.meenogroup.com/","",
 "China sourcing agency serving western SMB importers.",
 "head of partnerships","https://mywifequitherjob.com/china-sourcing-agent/","list-article","unverified",
 "Own site returned HTTP 500 (WordPress error) when opened on 2026-09-03."),
# ---------------- customs / trade counsel ----------------
("partner","customs attorney / trade counsel","Braumiller Law Group","https://www.braumillerlaw.com/","",
 "International trade and customs law firm; advises importers on classification disputes and would refer clients needing catalogue-scale classification.",
 "partner, customs practice","https://www.braumillerlaw.com/","company-site","verified",
 "Affiliated consultancy Braumiller Consulting sells classification services - see the excluded row."),
("partner","customs attorney / trade counsel","Grunfeld Desiderio Lebowitz Silverman & Klestadt (GDLSK)","https://www.gdlsk.com/","",
 "Customs and international trade law firm representing importers in classification and penalty matters.",
 "partner, customs practice","https://www.gdlsk.com/","company-site","verified",""),
("partner","customs attorney / trade counsel","Sandler, Travis & Rosenberg","https://www.sandlertravis.com/","",
 "Customs and trade law firm with a large importer client base.",
 "partner, customs practice","https://www.sandlertravis.com/","company-site","verified",
 "Page returned HTTP 200 but with an empty <title>; firm identity taken from the URL and known practice."),
("partner","customs attorney / trade counsel","Diaz Trade Law","https://www.diaztradelaw.com/","",
 "Customs-focused boutique advising small importers on CBP compliance and penalties.",
 "partner, customs practice","","company-site","unverified",
 "Site returned HTTP 403 to this agent on 2026-09-03."),
("partner","customs attorney / trade counsel","Thompson Hine SmarTrade","https://www.thompsonhinesmartrade.com/","",
 "International trade practice publishing a trade-alert blog read by importer compliance staff.",
 "partner, customs practice","https://www.thompsonhinesmartrade.com/","company-site","verified",""),
# ---------------- ecommerce / Amazon agencies ----------------
("partner","ecommerce agency","My Amazon Guy","https://myamazonguy.com/","",
 "Full-service Amazon agency whose private-label clients import from China; runs a formal partnership programme.",
 "head of partnerships","https://myamazonguy.com/mag-partnership/","company-site","verified",""),
("partner","ecommerce agency","Canopy Management","https://canopymanagement.com/","cites 1,000+ brands served on its own site",
 "Amazon and Walmart account-management agency for private-label brands.",
 "head of partnerships","https://canopymanagement.com/contact-us/","company-site","verified",""),
("partner","ecommerce agency","SalesDuo","https://salesduo.com/","",
 "Full-service Amazon agency; its brand clients carry the tariff exposure DutyLens measures.",
 "head of partnerships","hello@salesduo.com","company-site","verified",""),
("partner","ecommerce agency","SupplyKick","https://www.supplykick.com/","",
 "Full-service Amazon agency for consumer-goods brands.",
 "head of partnerships","info@supplykick.com","company-site","verified",""),
("partner","ecommerce agency","Amazon Growth Lab","https://www.amazongrowthlab.com/","",
 "Amazon marketing agency serving private-label sellers.",
 "head of partnerships","https://www.amazongrowthlab.com/contactus","company-site","verified",""),
("partner","ecommerce agency","SellerPlex","https://sellerplex.com/","",
 "Agency for 6-8 figure Amazon sellers covering supply chain as well as PPC.",
 "head of partnerships","https://sellerplex.com/","company-site","verified",
 "Homepage served a bot-verification interstitial; title read as 'Bot Verification'."),
("partner","ecommerce agency","Tinuiti","https://tinuiti.com/","",
 "Large independent performance agency with a substantial Amazon seller book.",
 "head of partnerships","https://tinuiti.com/contact/","company-site","verified",""),
("partner","seller software platform","Helium 10","https://www.helium10.com/","",
 "Amazon seller toolset; its user base is the sub-$5M private-label seller hit hardest by de minimis repeal.",
 "head of partnerships","https://www.helium10.com/","company-site","verified",""),
("partner","seller software platform","Jungle Scout","https://www.junglescout.com/","",
 "Amazon product-research platform with an existing partner programme; landed cost is a missing field in its product-research flow.",
 "head of partnerships","https://www.junglescout.com/partners-program/","company-site","verified",""),
# ---------------- channels: associations ----------------
("channel","trade association","National Customs Brokers & Forwarders Association of America (NCBFAA)","https://www.ncbfaa.org/","1,241 member companies found in its public directory (this research, 2026-09-03)",
 "The trade body for every customs broker and forwarder in the US; its member list is the partner channel and its events reach broker principals.",
 "membership director","https://www.ncbfaa.org/","association-directory","verified",""),
("channel","trade association","American Association of Exporters and Importers (AAEI)","https://aaei.org/","",
 "Importer-side trade association; members are exactly the compliance-owning importers DutyLens serves.",
 "membership director","https://aaei.org/contact-us/","association-directory","verified",
 "Member directory is behind a member login; only the public site was read."),
("channel","trade association","United States Fashion Industry Association (USFIA)","https://www.usfashionindustry.com/","",
 "Apparel importers' association; apparel carries the highest MFN duty rates and the most 301 exposure.",
 "membership director","https://www.usfashionindustry.com/about/partners","association-directory","verified",
 "Public member directory URL 404s; membership list not extractable."),
("channel","trade association","American Apparel & Footwear Association (AAFA)","https://www.aafaglobal.org/","",
 "Apparel and footwear brand association; members are import-dependent brands.",
 "membership director","https://www.aafaglobal.org/","association-directory","verified",
 "Member_List.aspx returns an error page unless signed in; no rows extractable."),
("channel","trade association","The Toy Association","https://www.toyassociation.org/","",
 "Toy importers' association and Toy Fair organiser; toys are almost entirely imported and heavily 301-exposed.",
 "membership director","https://www.toyassociation.org/toys/about-us/contact-us.aspx","association-directory","verified",
 "Member directory path 404s for anonymous visitors."),
("channel","trade association","Outdoor Industry Association","https://outdoorindustry.org/","",
 "Outdoor brand association; members import technical apparel and hard goods from Asia.",
 "membership director","https://outdoorindustry.org/partner/","association-directory","verified",
 "/members/ is a membership sales page, not a directory."),
("channel","trade association","Fashion Jewelry & Accessories Trade Association (FJATA)","https://fjata.org/","",
 "Jewellery and accessories importers' association; the category is almost entirely imported.",
 "membership director","https://fjata.org/index.php/contact-1/","association-directory","verified",
 "Member centre is login-gated."),
("channel","trade association","American Pet Products Association (APPA)","https://americanpetproducts.org/","",
 "Pet products association and Global Pet Expo organiser; the category is import-heavy.",
 "membership director","https://americanpetproducts.org/contact?hsLang=en","association-directory","verified",""),
("channel","trade association","Juvenile Products Manufacturers Association (JPMA)","https://www.jpma.org/","",
 "Juvenile products association; the category is import-heavy and CPSC-regulated.",
 "membership director","","association-directory","unverified",
 "Site returned HTTP 403 (Cloudflare interstitial) to this agent on 2026-09-03."),
("channel","trade association","International Compliance Professionals Association (ICPA)","https://www.icpainc.org/","",
 "Community of trade-compliance practitioners; both a referral channel and a source of importer contacts.",
 "membership director","support@icpainc.org","association-directory","verified",""),
# ---------------- channels: trade shows ----------------
("channel","trade show","ASD Market Week","https://asdonline.com/","811 exhibiting companies in the March 2026 public directory; 617 of them US-based",
 "The general-merchandise wholesale show where small US importers of variety goods exhibit; its public directory is the single richest ICP list found.",
 "event marketing manager","https://asdonline.com/about/contact-us/","directory","verified",""),
("channel","trade show","NY NOW","https://nynow.com/","499 exhibiting companies in the Winter 2026 public directory; 436 US-based",
 "Home, gift and lifestyle wholesale market; exhibitors are US brands importing from Asia.",
 "event marketing manager","https://nynow.com/partnerships/","directory","verified",""),
("channel","trade show","Outdoor Retailer","https://outdoorretailer.com/","278 exhibiting companies in the 2026 public directory; 243 US-based",
 "Outdoor brand trade show; exhibitors import technical goods with complex classification.",
 "event marketing manager","https://outdoorretailer.com/show-partners/","directory","verified",""),
("channel","trade show","Global Pet Expo","https://globalpetexpo.org/","about 400 exhibitors in the 2027 public exhibitor listing PDF",
 "Pet products show; exhibitors are import-dependent US brands.",
 "event marketing manager","https://globalpetexpo.org/contact?hsLang=en","directory","verified",""),
("channel","trade show","Toy Fair (The Toy Association)","https://toyassociation.org/","more than 720 exhibitors announced for 2026 by the organiser",
 "Toy trade show; exhibitors are US toy importers.",
 "event marketing manager","https://toyassociation.org/toyfair/contact-us.aspx","directory","verified",
 "Exhibitor directory on tfny2026.mapyourshow.com redirected to the show homepage for this agent."),
("channel","trade show","National Hardware Show / Hardlines Supplier Event","https://www.hardlinessupplierevent.com/","",
 "Hardware and home-improvement supplier show; exhibitors are importers of hard goods.",
 "event marketing manager","https://www.hardlinessupplierevent.com/en-us/media-partners.html","directory","verified",
 "Exhibitor list is client-side Algolia; index name not discoverable, so no rows extracted."),
("channel","trade show","MAGIC / Sourcing at MAGIC","https://www.magicfashionevents.com/","",
 "Apparel sourcing and wholesale show; US apparel importers attend to source from Asia.",
 "event marketing manager","","directory","unverified",
 "Site returned HTTP 403 (Cloudflare) to this agent on 2026-09-03."),
# ---------------- channels: communities, newsletters, podcasts ----------------
("channel","community / newsletter","eCommerceFuel (eComFuel)","https://www.ecommercefuel.com/","private community of 7- and 8-figure store owners (own site)",
 "Vetted community of exactly the $2M-$50M store owners in the ICP; runs a partner programme.",
 "community manager","https://www.ecommercefuel.com/ecommercefuel-partners/","company-site","verified",""),
("channel","community / newsletter","Million Dollar Sellers (MDS)","https://www.mds.co/","application-only, members at $1M+ annual revenue (own site)",
 "Application-only ecommerce founder community at the exact revenue band; has a partnership page.",
 "community manager","https://www.mds.co/partnership","company-site","verified",""),
("channel","community / newsletter","2PM (2PM Inc.)","https://2pml.com/","",
 "DTC commerce newsletter and the publisher of the DTC Power List; reaches DTC operators.",
 "editor","https://2pml.com/","company-site","verified",
 "Power List itself is largely subscriber-gated; only the public site was opened."),
("channel","community / newsletter","DTC Newsletter / Direct to Consumer","https://www.directtoconsumer.co/","",
 "Daily DTC newsletter and podcast reaching brand operators.",
 "editor","https://www.directtoconsumer.co/static/contact-us","company-site","verified",""),
("channel","community / newsletter","Lean Luxe","https://www.leanluxe.com/","",
 "Modern consumer-brand newsletter historically read by DTC founders.",
 "editor","","press","unverified",
 "leanluxe.com now resolves to an unrelated parked/hijacked site; no live URL recorded. Do not use the domain without re-checking."),
("channel","subreddit","r/FulfillmentByAmazon","https://www.reddit.com/r/FulfillmentByAmazon/","",
 "Where Amazon private-label sellers discuss tariff and customs shocks; named in the DutyLens idea as a launch channel.",
 "moderator","https://www.reddit.com/r/FulfillmentByAmazon/","directory","unverified",
 "reddit.com is on the blocked list for this environment (BRIEF s2.7). Name and public URL only; subreddit rules on self-promotion NOT verified."),
("channel","subreddit","r/importing","https://www.reddit.com/r/importing/","",
 "Subreddit for people importing goods into the US; directly on-topic for HTS and duty questions.",
 "moderator","https://www.reddit.com/r/importing/","directory","unverified",
 "reddit.com blocked in this environment. Name and public URL only; rules unverified."),
("channel","subreddit","r/AmazonSeller","https://www.reddit.com/r/AmazonSeller/","",
 "Amazon seller subreddit; audience is sub-$5M private-label sellers.",
 "moderator","https://www.reddit.com/r/AmazonSeller/","directory","unverified",
 "reddit.com blocked in this environment. Rules unverified."),
("channel","subreddit","r/dropship","https://www.reddit.com/r/dropship/","",
 "Dropshipper subreddit; the de minimis repeal broke this audience's unit economics.",
 "moderator","https://www.reddit.com/r/dropship/","directory","unverified",
 "reddit.com blocked in this environment. Rules unverified."),
("channel","subreddit","r/ecommerce","https://www.reddit.com/r/ecommerce/","",
 "General ecommerce subreddit where landed-cost questions surface.",
 "moderator","https://www.reddit.com/r/ecommerce/","directory","unverified",
 "reddit.com blocked in this environment. Rules unverified."),
("channel","subreddit","r/Freight","https://www.reddit.com/r/Freight/","",
 "Freight and customs practitioners; a partner-recruiting channel rather than a customer channel.",
 "moderator","https://www.reddit.com/r/Freight/","directory","unverified",
 "reddit.com blocked in this environment. Rules unverified."),
("channel","facebook group","Amazon FBA Competitive Edge (Facebook group)","https://www.facebook.com/groups/AmazonFBACompetitiveEdge/","",
 "Large public Amazon-seller Facebook group.",
 "group admin","https://www.facebook.com/groups/AmazonFBACompetitiveEdge/","directory","unverified",
 "facebook.com is on the blocked list (BRIEF s2.7). Name and public URL only; existence, size and rules NOT verified by this agent."),
("channel","facebook group","eCommerce Entrepreneurs (Facebook group)","https://www.facebook.com/groups/ecommerceentrepreneurs/","",
 "Public ecommerce founder Facebook group.",
 "group admin","https://www.facebook.com/groups/ecommerceentrepreneurs/","directory","unverified",
 "facebook.com blocked. Name and public URL only; existence and rules NOT verified."),
# ---------------- excluded: competitors ----------------
("excluded","competitor - HTS / landed cost software","Zonos","https://zonos.com/","",
 "Direct competitor: sells landed-cost calculation, HS classification and duty guarantee to ecommerce merchants.",
 "n/a","https://zonos.com/","company-site","verified","Named as the closest incumbent in the DutyLens idea record."),
("excluded","competitor - HTS / landed cost software","Avalara (incl. 3CE Technologies)","https://www.avalara.com/","",
 "Direct competitor: Avalara Tariff Code Classification classifies HS/HTS across 180+ countries for ecommerce catalogues.",
 "n/a","https://www.avalara.com/us/en/products/calculations/cross-border.html","company-site","verified",
 "www.3ce.com now redirects to Avalara's tariff/HS classification page, i.e. 3CE has been absorbed."),
("excluded","competitor - HTS / landed cost software","Gaia Dynamics","https://www.gaiadynamics.ai/","published credit tiers up to about $1,399/mo (competitor comparison table)",
 "Direct competitor: AI HS/HTS assignment plus a tariff engine covering 232/301/AD-CVD, explicitly aimed at SMB importers and independent brokers.",
 "n/a","https://gingercontrol.com/blog/trade-compliance-software-buyers-guide-2026","list-article","verified",""),
("excluded","competitor - HTS / landed cost software","GingerControl","https://gingercontrol.com/","self-serve credit packs from $10 (own comparison page)",
 "Direct competitor: iterative GRI-driven HTS classification with CROSS citations and tariff-stack monitoring - the same product thesis as DutyLens.",
 "n/a","https://gingercontrol.com/blog/trade-compliance-software-buyers-guide-2026","list-article","verified",""),
("excluded","competitor - HTS / landed cost software","TariffLens","https://www.tarifflens.ai/","",
 "Direct competitor: AI HTS classification sold to customs brokers.",
 "n/a","https://www.tarifflens.ai/","company-site","verified","Name is close enough to DutyLens's positioning to be a naming risk too."),
("excluded","competitor - HTS / landed cost software","Descartes Systems Group (CustomsInfo)","https://www.descartes.com/","",
 "Competitor: owns the deepest commercial tariff database and sells AI-assisted classification.",
 "n/a","https://gingercontrol.com/blog/trade-compliance-software-buyers-guide-2026","list-article","verified",""),
("excluded","competitor - HTS / landed cost software","e2open (formerly Amber Road)","https://www.e2open.com/","",
 "Competitor at the enterprise tier for global trade management including classification.",
 "n/a","https://www.e2open.com/","company-site","verified",""),
("excluded","competitor - HTS / landed cost software","KYG Trade","https://www.kygtrade.com/","",
 "Competitor: AI trade and tariff management software.",
 "n/a","https://www.kygtrade.com/contact-us","company-site","verified",""),
("excluded","competitor - HTS / landed cost software","CargoWise (WiseTech Global)","https://www.cargowise.com/","",
 "Competitor at the broker workflow layer; brokers using CargoWise are less likely to buy a separate tool.",
 "n/a","https://www.cargowise.com/","company-site","verified",""),
("excluded","competitor - HTS / landed cost software","SimplyDuty","https://www.simplyduty.com/","",
 "Competitor: self-serve duty and tax calculation aimed at small importers.",
 "n/a","https://www.simplyduty.com/contact/","company-site","verified",""),
("excluded","competitor - HTS / landed cost software","Easyship","https://www.easyship.com/","",
 "Competitor at the checkout layer: multi-carrier shipping with built-in duties and taxes for ecommerce.",
 "n/a","https://www.easyship.com/","company-site","verified",""),
("excluded","competitor - HTS / landed cost software","Passport (Passport Global)","https://passportglobal.com/","",
 "Competitor: cross-border shipping with compliance and landed cost for DTC brands.",
 "n/a","https://passportglobal.com/","company-site","verified",""),
("excluded","competitor - HTS / landed cost software","Global-e","https://www.global-e.com/","",
 "Competitor: cross-border ecommerce platform bundling duty calculation at checkout.",
 "n/a","https://www.global-e.com/","company-site","verified",""),
("excluded","competitor - HTS / landed cost software","SAP Global Trade Services (GTS)","https://www.sap.com/products/scm/global-trade-services.html","",
 "Enterprise competitor named in the 2026 trade-compliance vendor comparison.",
 "n/a","https://gingercontrol.com/blog/trade-compliance-software-buyers-guide-2026","list-article","secondary",
 "Vendor page not opened separately; taken from the comparison table."),
("excluded","competitor - HTS / landed cost software","Oracle Global Trade Management","https://www.oracle.com/scm/logistics/global-trade-management/","",
 "Enterprise competitor named in the 2026 trade-compliance vendor comparison.",
 "n/a","https://gingercontrol.com/blog/trade-compliance-software-buyers-guide-2026","list-article","secondary",
 "Vendor page not opened separately."),
("excluded","competitor - HTS / landed cost software","Thomson Reuters ONESOURCE Global Classification","https://tax.thomsonreuters.com/en/onesource","",
 "Enterprise competitor named in the 2026 trade-compliance vendor comparison.",
 "n/a","https://gingercontrol.com/blog/trade-compliance-software-buyers-guide-2026","list-article","secondary",
 "Vendor page not opened separately."),
("excluded","competitor - HTS / landed cost software","AEB","https://www.aeb.com/","",
 "Modular trade-compliance vendor named in the 2026 comparison; overlaps on classification.",
 "n/a","https://gingercontrol.com/blog/trade-compliance-software-buyers-guide-2026","list-article","secondary",
 "Vendor page not opened separately."),
("excluded","competitor - HTS / landed cost software","hclassify (Shopify app)","https://apps.shopify.com/hclassify","",
 "Direct competitor in the exact wedge: a Shopify app that assigns HS codes to a merchant's catalogue. Cited as best evidence in the DutyLens idea record.",
 "n/a","https://apps.shopify.com/hclassify","company-site","secondary",
 "Listing URL taken from the DutyLens idea record's evidence list; app store page not re-opened."),
("excluded","competitor - classification service","Tradewin","https://www.tradewin.net/","",
 "Sells HTS classification as a consulting service - a direct conflict per the DutyLens brief, not a referral partner.",
 "n/a","https://www.tradewin.net/about-us/contact-us/","company-site","verified",""),
("excluded","competitor - classification service","Braumiller Consulting Group","https://www.braumillerconsulting.com/","",
 "Trade-compliance consultancy selling classification work; conflicts with the DutyLens offer.",
 "n/a","https://www.braumillerconsulting.com/contact-us/","company-site","verified",
 "Its sister law firm Braumiller Law Group is listed separately as a partner."),
("excluded","competitor - classification service","Export Solutions, Inc.","https://www.exportsolutionsinc.com/","",
 "Import/export compliance consultancy offering managed classification services.",
 "n/a","https://www.exportsolutionsinc.com/contact/consultation/","company-site","verified",""),
("excluded","competitor - classification service","USA Customs Clearance (AFC International)","https://usacustomsclearance.com/","",
 "Sells customs consulting including HTS classification directly to small importers - same buyer, same job.",
 "n/a","https://usacustomsclearance.com/contact/","company-site","verified",""),
("excluded","competitor - classification service","Customs-Co","https://customs-co.com/","",
 "Sells HTS and ECCN classification consulting to US importers.",
 "n/a","https://customs-co.com/","company-site","unverified",
 "Site returned HTTP 403 to this agent on 2026-09-03; classification of the business taken from search-result text."),
("excluded","competitor - classification service","Freehand","https://www.freehand.ai/","",
 "Listed among HS-code classification software options for 2026.",
 "n/a","https://www.freehand.ai/","company-site","verified",
 "Its current homepage positions on spend governance rather than HS codes; overlap may have narrowed - recheck before treating as a live competitor."),
]
