#!/usr/bin/env python3
"""Derive the 15 launch states from BLS QCEW, reproducibly.

PLAN.md A11 says "the 15 states with most contractor activity" without defining the phrase. This
script defines it, in a way anyone can re-run and argue with:

    contractor activity = the number of PRIVATE ESTABLISHMENTS in NAICS 2382,
                          Building Equipment Contractors,
                          which is exactly electrical (23821) plus plumbing/HVAC (23822)
                          — the three trades StateReady covers and no others.

Establishments, not employment, because the unit that buys a licence-tracking subscription is a
BUSINESS, not a worker. NAICS 2382 rather than the whole of 238 because 238 also contains roofing,
concrete, drywall and painting, whose licensing rules we do not carry.

Source: BLS Quarterly Census of Employment and Wages open-data API, 2025 annual averages.
Note the lowercase quarter letter: .../<year>/a/industry/<naics>.csv works, uppercase A returns 404.

    python3 kb-scripts/rank_states.py            # print the ranking
    python3 kb-scripts/rank_states.py --write    # also write kb-data/_launch_states.json
"""
from __future__ import annotations

import csv
import datetime as dt
import io
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib_kb import KB_DATA, fetch                                            # noqa: E402

YEAR = 2025
NAICS = "2382"
URL = f"https://data.bls.gov/cew/data/api/{YEAR}/a/industry/{NAICS}.csv"
AGGLVL_STATE_NAICS4 = "56"      # state, NAICS 4-digit
OWN_PRIVATE = "5"
LAUNCH_N = 15

FIPS = {
    "01": "AL", "02": "AK", "04": "AZ", "05": "AR", "06": "CA", "08": "CO", "09": "CT", "10": "DE",
    "11": "DC", "12": "FL", "13": "GA", "15": "HI", "16": "ID", "17": "IL", "18": "IN", "19": "IA",
    "20": "KS", "21": "KY", "22": "LA", "23": "ME", "24": "MD", "25": "MA", "26": "MI", "27": "MN",
    "28": "MS", "29": "MO", "30": "MT", "31": "NE", "32": "NV", "33": "NH", "34": "NJ", "35": "NM",
    "36": "NY", "37": "NC", "38": "ND", "39": "OH", "40": "OK", "41": "OR", "42": "PA", "44": "RI",
    "45": "SC", "46": "SD", "47": "TN", "48": "TX", "49": "UT", "50": "VT", "51": "VA", "53": "WA",
    "54": "WV", "55": "WI", "56": "WY", "72": "PR",
}


def main() -> int:
    status, body, _ = fetch(URL)
    if status != 200:
        print(f"BLS QCEW returned {status} for {URL}", file=sys.stderr)
        return 1
    rows = list(csv.DictReader(io.StringIO(body.decode("utf-8", "replace"))))
    states = [r for r in rows
              if r["agglvl_code"] == AGGLVL_STATE_NAICS4
              and r["own_code"] == OWN_PRIVATE
              and r["area_fips"].endswith("000")
              and r["area_fips"][:2] in FIPS
              and FIPS[r["area_fips"][:2]] != "PR"]
    states.sort(key=lambda r: -int(r["annual_avg_estabs"]))
    total = sum(int(r["annual_avg_estabs"]) for r in states)

    print(f"NAICS {NAICS} Building Equipment Contractors, private, {YEAR} annual averages")
    print(f"{'#':>3} {'st':<3} {'establishments':>15} {'employment':>12} {'cum share':>10}")
    running = 0
    launch = []
    for i, r in enumerate(states, 1):
        st = FIPS[r["area_fips"][:2]]
        est = int(r["annual_avg_estabs"])
        running += est
        mark = " <- launch" if i <= LAUNCH_N else ""
        if i <= LAUNCH_N:
            launch.append({"rank": i, "state": st, "establishments": est,
                           "employment": int(r["annual_avg_emplvl"])})
        if i <= 20:
            print(f"{i:>3} {st:<3} {est:>15,} {int(r['annual_avg_emplvl']):>12,} "
                  f"{100*running/total:>9.1f}%{mark}")
    covered = sum(x["establishments"] for x in launch)
    print(f"\nlaunch 15 cover {covered:,} of {total:,} US establishments = {100*covered/total:.1f}%")

    if "--write" in sys.argv:
        out = {
            "_comment": "Generated by kb-scripts/rank_states.py. The definition of 'the 15 states with "
                        "most contractor activity' (PLAN.md A11), with the numbers it was derived from.",
            "generated_at": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
            "definition": "private establishments, NAICS 2382 Building Equipment Contractors "
                          "(= 23821 electrical + 23822 plumbing/HVAC), BLS QCEW annual averages",
            "source_url": URL, "source_year": YEAR,
            "us_total_establishments": total,
            "launch_share_pct": round(100 * covered / total, 1),
            "states": launch,
            "next_in_line": [{"rank": i, "state": FIPS[r["area_fips"][:2]],
                              "establishments": int(r["annual_avg_estabs"])}
                             for i, r in enumerate(states, 1) if LAUNCH_N < i <= LAUNCH_N + 5],
        }
        (KB_DATA / "_launch_states.json").write_text(json.dumps(out, indent=2) + "\n")
        print(f"wrote {KB_DATA / '_launch_states.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
